name: Hourly cron job
on:
  schedule:
    - cron: '0 12 * * 6' # every saturday at 8am
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Hourly cron job
        run: |
          curl --GET --url 'https://www.tomlu.me/api/emailSubs'